apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-apiDocs
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    github.com/project-slug: vl00920760/swagger-petstore
    lighthouse.com/website-url: https://backstage.io
spec:
  type: OpenAPI
  owner: vivek
  lifecycle: experimental
